apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "helper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{- include "helper.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
  selector:
    matchLabels:
{{- include "helper.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{- include "helper.labels" . | indent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      nodeSelector:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      containers:
      - name: {{ template "helper.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        env:
        {{- if .Values.basePathOverride }}
        - name: BASE_PATH
          value: {{ .Values.basePathOverride | quote }}
        {{- end }}
        {{- if .Values.podNodesSelectorPathOverride }}
        - name: POD_NODES_SELECTOR_PATH
          value: {{ .Values.podNodesSelectorPathOverride | quote }}
        {{- end }}
        - name: POD_NODES_SELECTOR_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "helper.fullname" . }}-config
              key: podNodeSelectorConfig
        {{- if .Values.podTolerationRestrictionPathOverride }}
        - name: POD_TOLERATION_RESTRICTION_PATH
          value: {{ .Values.podTolerationRestrictionPathOverride | quote }}
        {{- end }}
        - name: POD_TOLERATION_RESTRICTION_CONFIG
          valueFrom:
            configMapKeyRef:
              name: {{ template "helper.fullname" . }}-config
              key: podTolerationRestrictionConfig
        ports:
        - name: https
          containerPort: 8443
        volumeMounts:
        - name: tls
          mountPath: /run/secrets/tls
          readOnly: true
      volumes:
      - name: tls
        secret:
          secretName: {{ template "helper.fullname" . }}-tls
