---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration 
metadata:
  name: {{ template "helper.fullname" . }}
  labels:
{{- include "helper.labels" . | indent 4 }}
webhooks:
- name: "pod-nodes-selector.{{ template "helper.webhook-server-name" . }}"
  admissionReviewVersions: [v1]
  sideEffects: None
  {{- if .Values.namespaceSelector }}
  namespaceSelector:
{{ toYaml .Values.namespaceSelector | indent 4 }}
  {{- end }}
  clientConfig: 
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ .Values.service.name }}
      path: '/{{ default "mutate" .Values.basePathOverride }}/{{ default "pod-nodes-selector" .Values.podNodesSelectorPathOverride }}' 
    caBundle: '{{ .Files.Get "ssl/ca.crt" | b64enc }}'
  rules: 
  - operations: 
    - CREATE
    apiGroups:
    - ""
    apiVersions:
    - "*"
    resources:
    - pods
- name: "pod-toleration-restriction.{{ template "helper.webhook-server-name" . }}"
  admissionReviewVersions: [v1]
  sideEffects: None
  {{- if .Values.namespaceSelector }}
  namespaceSelector:
{{ toYaml .Values.namespaceSelector | indent 4 }}
  {{- end }}
  namespaceSelector:
  clientConfig: 
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ .Values.service.name }}
      path: '/{{ default "mutate" .Values.basePathOverride }}/{{ default "pod-toleration-restriction" .Values.podTolerationRestrictionPathOverride }}' 
    caBundle: '{{ .Files.Get "ssl/ca.crt" | b64enc }}'
  rules: 
  - operations: 
    - CREATE
    apiGroups:
    - ""
    apiVersions:
    - "*"
    resources:
    - pods
