---
name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      - name: Check out code
        uses: actions/checkout@v1
      - name: build binary and image
        run: make docker
      - name: tag image
        run: docker tag liangrog/admission-webhook-server:latest liangrog/admission-webhook-server:${{ github.ref }}
      - name: docker login
        run: docker login -u liangrog -p ${{ secrets.dockerhub }}
      - name: push tag latest 
        run: docker push liangrog/admission-webhook-server:latest
      - name: push tag versioned
        run: docker push liangrog/admission-webhook-server:${{ github.ref }}
