---
name: Release
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.20
      - name: Check out code
        uses: actions/checkout@v1
      - name: build binary and image
        run: make docker
      - name: Get tag version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: tag image
        run: docker tag autermann/admission-webhook-server:latest autermann/admission-webhook-server:${{ steps.get_version.outputs.VERSION }}
      - name: docker login
        run: docker login -u autermann -p ${{ secrets.dockerhub }}
      - name: push tag latest 
        run: docker push autermann/admission-webhook-server:latest
      - name: push tag versioned
        run: docker push autermann/admission-webhook-server:${{ steps.get_version.outputs.VERSION }}
